name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4

    - name: Setup Node.js
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: '20'
        cache: 'npm'  # Added caching for faster installs

    - name: Install dependencies
      run: npm ci  # Changed to npm ci for reproducible builds

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Zip artifact
      run: zip -r simple-app.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Fixed: Updated to v4
      with:
        name: simple-app-artifact
        path: simple-app.zip
