name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Zip artifact
        run: zip -r simple-app1.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-app1-artifact
          path: simple-app1.zip

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      PORT: 3000
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: simple-app1-artifact
          path: ./artifact

      - name: Unzip artifact
        run: unzip ./artifact/simple-app1.zip -d ./artifact

      - name: Install dependencies
        run: npm install
        working-directory: ./artifact

      - name: Start application
        run: npm start
        working-directory: ./artifact
